Datastore tests
googleinterns/step11-2020 pull request #68
Opened 2020-07-16 05:04 UTC by muditg317

its only 49 lines of logic changes. the other 496 are tests.

2020-07-17 21:51 UTC, linguistrix requested changes
You can merge some of the tests together. If you are calling a function with a given set of inputs you can test for all the relevant outputs in one test.

2020-07-17 21:51 UTC, linguistrix commented on src/test/java/com/google/sps/data/DatastoreAccessTest.java
> + * TO RUN PROJECT WITHOUT TESTS RUN COMMAND: mvn package appengine:run -DskipTests Basic structure
This is becoming run-on. Add paragraphs

2020-07-17 21:51 UTC, linguistrix commented on src/test/java/com/google/sps/data/DatastoreAccessTest.java
> +    final String testUserID = "1234";
You don't need the temp var, just inline it.

2020-07-20 22:38 UTC, sagunb approved these changes

2020-07-20 22:38 UTC, merged