add basic outline of questionnaire form
googleinterns/step11-2020 pull request #8
Opened 2020-06-23 00:29 UTC by ThomasQuesadilla

Added some jinja templating to condense selection html. Still working on applying CSS and more functionality (e.g. different questions based on selection of the previous screen).

Apologies for the long PR, the only new thing that was added from the PR in original repo is the countries/states parsing and templating so that no 196 line selection would exist in the html template.

2020-06-23 21:24 UTC, sagunb requested changes

2020-06-23 21:24 UTC, sagunb commented on src/main/java/com/google/sps/servlets/QuestionnaireServlet.java
> +            this.getClass().getResource("/templates/questionnaire.html"), Charsets.UTF_8);
move all of these to the constants file

2020-06-23 21:24 UTC, sagunb commented on src/main/java/com/google/sps/servlets/QuestionnaireServlet.java
> +            this.getClass().getResource("/templates/questionnaire.html"), Charsets.UTF_8);
these = hard coded resource locations

2020-06-23 21:24 UTC, sagunb commented on src/main/resources/templates/questionnaire.html
> +      <input type="checkbox" name="caucasian" value="caucasian">
prefer to have these multiple choice options generated in the backend this way the list of valid options is always in sync with what the backend can accept.

2020-06-26 21:58 UTC, linguistrix requested changes

2020-06-26 21:58 UTC, linguistrix commented on src/main/java/com/google/sps/data/TimeZoneInfo.java
> +  private static final double MILLISECONDS_TO_HOURS = 3600000.0;
nit but better to name it something that makes it clear what direction the conversion is in.

MILLISECONDS_PER_HOUR for eg. makes it clear.

2020-06-29 19:22 UTC, sagunb approved these changes

2020-06-29 19:23 UTC, merged